### 
# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Amazon",
    "symbol": "AMZN",
    "price": 3200,
    "image": "AMZN.png"
}

### 

POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "NVIDIA",
    "symbol": "NVDA",
    "price": 450,
    "image": "NVDA.png"
}

### 
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Mercado Livre",
    "symbol": "MELI",
    "price": 1200,
    "image": "MELI.png"
}

### 
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Meta",
    "symbol": "META",
    "price": 280,
    "image": "META.png"
}

### 
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Salesforce",
    "symbol": "CRM",
    "price": 210,
    "image": "CRM.png"
}

###
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Google",
    "symbol": "GOL3",
    "price": 3000,
    "image": "GOOGL.png"
}

###
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Coca-Cola",
    "symbol": "KO",
    "price": 37,
    "image": "KO.png"
}

###
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Mc-Donalds",
    "symbol": "MCD",
    "price": 37,
    "image": "MCD.png"
}
###
@assetId = {{ createAsset.response.body.id }}
###
GET http://localhost:3000/assets

###
GET http://localhost:3000/assets/A1

### 
# @name createWallet
POST http://localhost:3000/wallets

###
@walletId = {{ createWallet.response.body._id }}
###
GET http://localhost:3000/wallets

###
GET http://localhost:3000/wallets/{{walletId}}

### 
POST http://localhost:3000/wallets/{{walletId}}/assets
Content-Type: application/json

{
    "assetId": "{{assetId}}",
    "shares" : 100
}

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "walletId": "{{ walletId }}",
    "assetId": "{{ assetId }}",
    "shares": 10,
    "price": 100,
    "type": "BUY"
}

###
GET http://localhost:3000/orders?walletId=791531d0-9f71-4d7d-a3f5-9388040481f6